### PR TITLE
Changed the name that displays in ModMenu and made it a sub-mod of carpet.

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Changed the name that displays in mod menu because:

a) The mod name is the only one in my mod list (both ModMenu AND MultiMc mod list) that has lowercase letters which is triggering, and most other mods also use capitals.

_

> 
> b) For some reason, maybe the lowercase, maybe the hyphen, the mod is right at the bottom breaking the alphabetical order (Only ModMenu, not MultiMc mod list) . This also occurred on another mod with lowercase letters and a hyphen a while back, so I created a pr on that mod as well to fix the issue.
> 
> I built the mod (from my fork) and it works fine now; both issues have been fixed with this commit. The reason there are two commits is that the first time I tried I made two changes, changing the mod name and also the mod id. I undid the mod id change in the second mod because the name was invalid, but just changing the mod name fixes both issues.

_

THIS SECTION IS IRRELEVANT DUE TO THE BUG BEING FIXED IN MODMENU BUT I STUPIDLY DELETED MY FORK TO SORRY. tHE FIRST PART STILL APPLIES, SO I GUESS THIS PART OF THE PR IS STILL RELEVANT...

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
Changed fabric.mod.json to make it so that aleph-carpet displays as a sub-part of carpet in modmenu, as Carpet TIS Additions has already done.

**Comment by DragonEggBedrockBreaking** [comment]
Sorry, I updated the README on the wrong branch... Imma fix that and comment when I undo it.

**Comment by DragonEggBedrockBreaking** [comment]
OK, fixed it, should be fine now... Sorry abt that...

**Review by whoImT — APPROVED** [review]

**Comment by DragonEggBedrockBreaking** [comment]
that last commit was just to update my fork with newer changes you guys added, don't worry about that

**Comment by DragonEggBedrockBreaking** [comment]
This is extremely messy with commits everywhere and random messages, so imma re-do this

**Pull request closed without merging**
